site_name: ChemRefine
theme:
  name: material

nav:
  - Home: home.md
  - Install: INSTALL.md
  - Tutorials:
      - Overview: tutorials/index.md
      - Conformer Sampling: tutorials/conformer_sampling.md
      - Transition State Finding: tutorials/ts_finding.md 
      - Host-Guest Docking and Microsolvation: tutorials/host-guest.md
      - MLIP Training and Normal Mode Sampling: tutorials/mlip_training.md
      - Redox: tutorials/redox.md
      - Spin: tutorials/spin.md

  