"""Bash that orchestrates the ExtOpt HTTP server alongside ORCA in one SLURM job.

The two engines that drive ORCA through an external optimizer (MLFF and
PySCF) emit a SLURM ``run_block`` that spins up the shared
:mod:`chemrefine.engines._extopt.server`, polls ``/healthz`` until it is
ready, runs ORCA, and tears the server down on exit. This module owns
that bash so neither engine ends up importing helpers from the other.
"""

from __future__ import annotations

import shlex

from chemrefine.engines._extopt.base import DEFAULT_BIND_HOST, SERVER_URL_FILENAME

_SERVER_READY_TIMEOUT_SECONDS: int = 120


def _server_command(
    *,
    backend: str,
    extra_tokens: list[str],
) -> str:
    """Build the ``python -m chemrefine.engines._extopt.server ...`` command.

    ``extra_tokens`` is a flat list of CLI tokens (e.g.
    ``["--foo", "bar", "--baz"]``) emitted by the backend's
    :meth:`BaseExtOptCalculator.server_cli_from_options`. Keeping them
    as one list keeps key-value flags and bool flags symmetric.
    """
    parts = [
        "python -m chemrefine.engines._extopt.server",
        f"--backend {shlex.quote(backend)}",
        f"--bind {DEFAULT_BIND_HOST}:0",
        '--url-file "$URL_FILE"',
        '--log-file "$LOG_FILE"',
        "--log-level INFO",
    ]
    parts.extend(shlex.quote(token) for token in extra_tokens)
    return " ".join(parts)


def _build_extopt_run_block(
    *,
    server_cmd: str,
    orca_executable: str,
    inp_name: str,
    out_name: str,
) -> str:
    """Return the bash ``run_block`` that orchestrates the ExtOpt server + ORCA.

    The block:

    * Binds the server on a kernel-assigned port (sidecar URL file).
    * Loops up to ``_SERVER_READY_TIMEOUT_SECONDS`` polling ``/healthz``,
      exiting fast if the server process dies during startup.
    * Wraps cleanup in ``trap _on_extopt_exit EXIT INT TERM`` so SLURM
      cancellation (SIGTERM), Ctrl-C (SIGINT), or normal exit all reach
      the cleanup path; ``kill -TERM`` + ``wait`` gives the server a
      chance to release GPU memory cleanly.
    """
    return (
        '# ExtOpt server lifecycle (generated by ChemRefine MLFF/PySCF engine)\n'
        f'LOG_FILE="$OUTPUT_DIR/server_${{SLURM_JOB_ID:-$$}}.log"\n'
        f'URL_FILE="$WORK_DIR/{SERVER_URL_FILENAME}"\n'
        f'SERVER_TIMEOUT={_SERVER_READY_TIMEOUT_SECONDS}\n'
        f'{server_cmd} &\n'
        'SERVER_PID=$!\n'
        '\n'
        '_on_extopt_exit() {\n'
        '  if [ -n "${SERVER_PID:-}" ]; then\n'
        '    kill -TERM "$SERVER_PID" 2>/dev/null || true\n'
        '    wait "$SERVER_PID" 2>/dev/null || true\n'
        '  fi\n'
        '}\n'
        'trap _on_extopt_exit EXIT INT TERM\n'
        '\n'
        '# Wait for /healthz; bail out fast if the server crashed during startup.\n'
        'ready=\n'
        'for i in $(seq 1 "$SERVER_TIMEOUT"); do\n'
        '  if [ -s "$URL_FILE" ] \\\n'
        '     && SERVER_URL=$(cat "$URL_FILE") \\\n'
        '     && curl -fsS --max-time 2 "http://${SERVER_URL}/healthz" >/dev/null; then\n'
        '    echo "ExtOpt server ready at $SERVER_URL after ${i}s"\n'
        '    ready=1\n'
        '    break\n'
        '  fi\n'
        '  if ! ps -p "$SERVER_PID" >/dev/null; then\n'
        '    echo "ExtOpt server crashed during startup; log follows:" >&2\n'
        '    cat "$LOG_FILE" >&2 || true\n'
        '    exit 1\n'
        '  fi\n'
        '  sleep 1\n'
        'done\n'
        '[ -n "$ready" ] || {\n'
        '  echo "ExtOpt server did not become ready within ${SERVER_TIMEOUT}s; log follows:" >&2\n'
        '  cat "$LOG_FILE" >&2 || true\n'
        '  exit 1\n'
        '}\n'
        '\n'
        'export OMP_NUM_THREADS=1\n'
        f'{orca_executable} {inp_name} > "$OUTPUT_DIR/{out_name}"'
    )
