"""SLURM mechanics: script generation, ``sbatch`` submission, ``squeue`` polling.

This module is engine-agnostic. It knows how to assemble a SLURM script
from a cluster-specific header template plus an engine-provided
``run_block`` (the bash that actually invokes the calculation), how to
submit that script with ``sbatch``, and how to poll job completion with
``squeue``. PAL-budget bookkeeping lives in :mod:`chemrefine.throttle`;
this module only deals with the SLURM commands themselves.

The :func:`submit` and :func:`is_finished` functions shell out to real
binaries. Tests patch ``subprocess.run`` to avoid needing a live SLURM
cluster.
"""

from __future__ import annotations

import getpass
import logging
import re
import subprocess
from pathlib import Path

from chemrefine.errors import JobSubmissionError

logger = logging.getLogger(__name__)

_PAL_PATTERNS = (
    re.compile(r"nprocs\s+(\d+)", re.IGNORECASE),
    re.compile(r"\bPAL(\d+)\b", re.IGNORECASE),
    re.compile(r"^\s*PAL\s+(\d+)\b", re.IGNORECASE | re.MULTILINE),
)
_SBATCH_OVERRIDES = ("--ntasks", "--cpus-per-task", "--job-name", "--output", "--error")
_JOB_ID_RE = re.compile(r"\b(\d+)\b")


# ---------------------------------------------------------------------------
# PAL parsing
# ---------------------------------------------------------------------------


def parse_pal(input_file: str | Path) -> int:
    """Return the PAL / ``nprocs`` value declared in an ORCA input file.

    Falls back to ``1`` when no PAL directive is found, matching ORCA's
    own default for serial runs.
    """
    text = Path(input_file).read_text(encoding="utf-8")
    for pattern in _PAL_PATTERNS:
        m = pattern.search(text)
        if m:
            return int(m.group(1))
    return 1


# ---------------------------------------------------------------------------
# Script assembly
# ---------------------------------------------------------------------------


def build_script(
    *,
    job_name: str,
    pal: int,
    template_path: Path,
    script_path: Path,
    input_path: Path,
    output_dir: Path,
    scratch_dir: Path,
    run_block: str,
    save_scratch: bool = False,
) -> Path:
    """Assemble a SLURM script at ``script_path`` and return its path.

    Parameters
    ----------
    job_name:
        Becomes ``#SBATCH --job-name`` and the stem of stdout / stderr files.
    pal:
        Becomes ``#SBATCH --ntasks``. ``--cpus-per-task`` is pinned to 1.
    template_path:
        Cluster-specific SLURM header (e.g. ``cpu.slurm.header``). Any
        ``--ntasks`` / ``--cpus-per-task`` / ``--job-name`` /
        ``--output`` / ``--error`` directives the user wrote there are
        dropped and replaced with our overrides so PAL stays consistent.
    script_path:
        Output path for the generated ``.slurm`` script (parents will be
        created).
    input_path:
        The engine input file. Copied into ``$SCRATCH_DIR`` so the
        calculation runs on local fast storage.
    output_dir:
        Where to copy results back to once the calculation finishes.
    scratch_dir:
        Base directory under which a unique per-job scratch path is
        created. The script removes the per-job scratch dir on exit
        unless ``save_scratch`` is true.
    run_block:
        Engine-specific bash that actually invokes the calculation. It
        runs after ``cd $SCRATCH_DIR``; it can reference ``$OUTPUT_DIR``,
        ``$SCRATCH_DIR``, and the basename of the input file.
    """
    if not template_path.is_file():
        raise FileNotFoundError(f"SLURM header template {template_path} not found")

    sbatch_lines: list[str] = []
    body_lines: list[str] = []
    for raw in template_path.read_text(encoding="utf-8").splitlines():
        stripped = raw.strip()
        if stripped.startswith("#SBATCH"):
            if any(flag in stripped for flag in _SBATCH_OVERRIDES):
                continue
            sbatch_lines.append(raw.rstrip())
        else:
            body_lines.append(raw.rstrip())

    sbatch_lines.append(f"#SBATCH --job-name={job_name}")
    sbatch_lines.append(f"#SBATCH --output=slurm_{job_name}.out")
    sbatch_lines.append(f"#SBATCH --error=slurm_{job_name}.err")
    sbatch_lines.append(f"#SBATCH --ntasks={pal}")
    sbatch_lines.append("#SBATCH --cpus-per-task=1")

    cleanup = (
        "echo 'scratch dir kept (save_scratch=True)'"
        if save_scratch
        else "rm -rf $SCRATCH_DIR"
    )

    script_lines = [
        "#!/bin/bash",
        "",
        *sbatch_lines,
        "",
        *body_lines,
        "",
        "# Scratch + run block (generated by ChemRefine)",
        "set -euo pipefail",
        "timestamp=$(date +%Y%m%d%H%M%S)",
        "random_str=$(tr -dc a-z0-9 </dev/urandom | head -c 8)",
        f"export SCRATCH_DIR={scratch_dir}/ChemRefine_${{SLURM_JOB_ID:-local}}_${{timestamp}}_${{random_str}}",
        f"export OUTPUT_DIR={output_dir}",
        "mkdir -p $SCRATCH_DIR",
        f"cp {input_path} $SCRATCH_DIR/",
        "cd $SCRATCH_DIR",
        "",
        run_block,
        "",
        'cp *.out *.xyz $OUTPUT_DIR/ 2>/dev/null || true',
        cleanup,
        "",
    ]

    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text("\n".join(script_lines), encoding="utf-8")
    return script_path


# ---------------------------------------------------------------------------
# sbatch / squeue
# ---------------------------------------------------------------------------


def submit(script_path: str | Path, *, sbatch_cmd: str = "sbatch") -> str:
    """Submit a SLURM script and return the assigned job ID.

    Raises :class:`~chemrefine.errors.JobSubmissionError` if ``sbatch``
    exits non-zero or its output does not contain a numeric job ID.
    """
    try:
        result = subprocess.run(
            [sbatch_cmd, str(script_path)],
            capture_output=True,
            text=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        raise JobSubmissionError(f"sbatch failed for {script_path}: {e}") from e
    m = _JOB_ID_RE.search(result.stdout)
    if not m:
        raise JobSubmissionError(
            f"could not parse job ID from sbatch output: {result.stdout!r}"
        )
    job_id = m.group(1)
    logger.info("submitted %s as job %s", script_path, job_id)
    return job_id


def is_finished(job_id: str, *, squeue_cmd: str = "squeue") -> bool:
    """Return True if ``job_id`` is no longer in the current user's ``squeue``."""
    user = getpass.getuser()
    try:
        result = subprocess.run(
            [squeue_cmd, "-u", user, "-o", "%i"],
            capture_output=True,
            text=True,
            check=True,
        )
    except subprocess.CalledProcessError:
        # squeue is transient on busy clusters; treat as "not finished" and try again later.
        return False
    lines = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    # First line is the header ("JOBID"); drop it before checking membership.
    running = lines[1:] if lines else []
    return job_id not in running
