"""HTTP client + ExtOpt wrapper entry point for MLFF-driven ORCA runs.

ORCA invokes the wrapper script generated by :func:`build_wrapper_script`
once per optimization step. The wrapper:

1. Reads ORCA's ``{base}.extinp.tmp`` (atom types, coordinates, charge,
   multiplicity, ``dograd`` flag, ``ncores``).
2. POSTs the payload to ``http://<bind>/calculate``.
3. Writes the returned energy + gradient to ``{base}.engrad`` so ORCA
   can take its next step.

This module ships the verifiable parts in full:

* :func:`parse_args` — the CLI surface ORCA's wrapper script calls.
* :func:`submit_calculation` — the pure HTTP RPC (mockable via
  ``requests``).

The :func:`main` glue that wires ExtOpt file I/O around them is still
a placeholder because the ``.extinp.tmp`` / ``.engrad`` format helpers
live in :mod:`chemrefine.engines.orca.extopt` and are themselves
awaiting a real ORCA-run fixture.
"""

from __future__ import annotations

import argparse
import json
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from chemrefine.errors import JobFailureError

DEFAULT_BIND = "127.0.0.1:8888"
DEFAULT_TIMEOUT = 600.0
"""Seconds before a single ``/calculate`` request times out (matches v3)."""


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Return the wrapper script's parsed CLI namespace.

    Flags match the v3 ``client.py`` from ``main`` byte-for-byte so the
    SLURM ``run_block`` produced by :class:`~chemrefine.engines.mlff.engine.MlffEngine`
    keeps working.
    """
    parser = argparse.ArgumentParser(prog="chemrefine-mlff-client")
    parser.add_argument("--bind", default=DEFAULT_BIND, help="host:port of the MLFF server")
    parser.add_argument("--model_name", default="uma-s-1", help="MLFF model identifier")
    parser.add_argument("--task_name", default="omol", help="MLFF task name")
    parser.add_argument("--device", default="cuda", help="cuda | cpu")
    parser.add_argument("inputfile", help="ORCA-written ``.extinp.tmp`` to relay")
    return parser.parse_args(argv)


def submit_calculation(
    *,
    server_url: str,
    atom_types: list[str],
    coordinates: list[list[float]],
    charge: int,
    mult: int,
    dograd: bool,
    nthreads: int,
    timeout: float = DEFAULT_TIMEOUT,
) -> tuple[float, list[list[float]]]:
    """Send one geometry to the MLFF server; return ``(energy, gradient)``.

    Raises :class:`JobFailureError` on any HTTP / connection / JSON
    error so the calling step records a clean failure instead of
    crashing with a stack trace.
    """
    payload = {
        "atom_types": atom_types,
        "coordinates": coordinates,
        "charge": charge,
        "mult": mult,
        "dograd": dograd,
        "nthreads": nthreads,
    }
    request = Request(
        f"http://{server_url}/calculate",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(request, timeout=timeout) as response:
            body = response.read()
    except HTTPError as e:
        raise JobFailureError(f"MLFF server returned HTTP {e.code}: {e.reason}") from e
    except URLError as e:
        raise JobFailureError(f"MLFF server unreachable at {server_url}: {e.reason}") from e
    try:
        data = json.loads(body)
    except json.JSONDecodeError as e:
        raise JobFailureError(f"MLFF server returned non-JSON body: {body!r}") from e
    if "error" in data:
        raise JobFailureError(f"MLFF server error: {data['error']}")
    try:
        return float(data["energy"]), list(data["gradient"])
    except (KeyError, TypeError, ValueError) as e:
        raise JobFailureError(f"MLFF server response missing fields: {data!r}") from e


def main() -> int:
    """ORCA-invoked entry point — glue between ``.extinp.tmp`` and ``.engrad``.

    TODO: wire :mod:`chemrefine.engines.orca.extopt` (``read_extinp`` +
    ``write_engrad``) around :func:`submit_calculation` once a real
    ORCA ExtOpt run is captured. The shape will be::

        args = parse_args(sys.argv[1:])
        atom_types, coords, charge, mult, ncores, dograd = read_extinp(args.inputfile)
        energy, gradient = submit_calculation(
            server_url=args.bind, atom_types=atom_types, coordinates=coords,
            charge=charge, mult=mult, dograd=dograd, nthreads=ncores,
        )
        write_engrad(
            path=args.inputfile.replace(".extinp.tmp", ".engrad"),
            n_atoms=len(atom_types),
            energy_hartree=energy,
            gradients_hartree_per_bohr=gradient,
        )
        return 0
    """
    raise NotImplementedError(
        "MLFF client main not yet ported — see TODO in engines/mlff/client.py"
    )
