"""ORCA-driven MLFF engine.

This engine reuses the entire ORCA submission pipeline (input writer,
SLURM, output parser) and only differs in two ways:

1. The generated ORCA ``.inp`` carries a ``%method ... ProgExt ... end``
   block pointing at a wrapper script. ORCA invokes that wrapper at each
   optimization step; the wrapper relays the geometry to a long-running
   MLFF HTTP server and pipes the resulting energy + gradient back as
   ``.engrad``.
2. The SLURM ``run_block`` starts that server before ORCA and tears it
   down afterwards.

Backend selection / model name / bind address are read from
``step.options`` in the YAML. The actual server module
(``chemrefine.engines.mlff.server``) is a placeholder until the ExtOpt
protocol parts get a real fixture to verify against.
"""

from __future__ import annotations

import logging
import shlex
from pathlib import Path

from chemrefine.engines.base import register
from chemrefine.engines.orca.engine import OrcaEngine
from chemrefine.state import StepContext

logger = logging.getLogger(__name__)


@register("mlff")
class MlffEngine(OrcaEngine):
    """ORCA optimisation backed by an MLFF gradient server."""

    name = "mlff"
    supports_nms = False  # frequencies via MLFF aren't validated yet

    # -- ORCA input customisation -----------------------------------------

    def _extra_blocks(self, ctx: StepContext) -> str:
        """Emit a ``%method ProgExt "<wrapper>"`` block tied to this step's bind address."""
        wrapper = self._wrapper_path(ctx)
        bind = self._bind_address(ctx)
        return (
            "%method\n"
            f'  ProgExt "{wrapper}"\n'
            f'  Ext_Params "--bind {bind}"\n'
            "end"
        )

    # -- SLURM customisation ----------------------------------------------

    def _run_block(self, ctx: StepContext, inp_path: Path, out_path: Path) -> str:
        """Spin up the MLFF server, run ORCA, then tear the server down.

        The server entry point is :func:`chemrefine.engines.mlff.server.main`
        (currently a placeholder). The wrapper script written under
        ``$SCRATCH_DIR`` POSTs the per-step geometry to that server.
        """
        options = ctx.step_cfg.options or {}
        model_name = options.get("model_name") or options.get("model") or "uma-s-1"
        task_name = options.get("task_name") or options.get("task") or "omol"
        device = options.get("device", "cuda")
        bind = self._bind_address(ctx)

        cmd = (
            "python -m chemrefine.engines.mlff.server"
            f" --model {shlex.quote(str(model_name))}"
            f" --task-name {shlex.quote(str(task_name))}"
            f" --device {shlex.quote(str(device))}"
            f" --bind {shlex.quote(str(bind))}"
        )

        return (
            "# Start MLFF server in background\n"
            f"{cmd} > $OUTPUT_DIR/server.log 2>&1 &\n"
            "SERVER_PID=$!\n"
            "trap 'kill $SERVER_PID 2>/dev/null' EXIT\n"
            "# Give the server a moment to bind its socket.\n"
            "sleep 10\n"
            "export OMP_NUM_THREADS=1\n"
            f"{ctx.orca_executable} {inp_path.name} > $OUTPUT_DIR/{out_path.name}\n"
            "kill $SERVER_PID 2>/dev/null || true"
        )

    # -- Helpers -----------------------------------------------------------

    def _wrapper_path(self, ctx: StepContext) -> Path:
        """Path to the ExtOpt wrapper script for this step.

        The script is generated by the ExtOpt protocol helpers (currently
        placeholder — see :mod:`chemrefine.engines.orca.extopt`). The
        engine resolves the canonical path so the ORCA input can
        reference it before the script is written.
        """
        return (ctx.step_dir / "mlff_extopt.sh").resolve()

    def _bind_address(self, ctx: StepContext) -> str:
        """Resolve the ``host:port`` the MLFF server will bind to."""
        options = ctx.step_cfg.options or {}
        return options.get("bind", "127.0.0.1:8888")
