"""ORCA-driven MLFF engine.

This engine reuses the entire ORCA submission pipeline (input writer,
SLURM, output parser) and only differs in two ways:

1. The generated ORCA ``.inp`` carries a ``%method ... ProgExt ... end``
   block pointing at a wrapper script. ORCA invokes that wrapper at each
   optimization step; the wrapper relays the geometry to a long-running
   ExtOpt HTTP server and pipes the resulting energy + gradient back as
   ``.engrad``.
2. The SLURM ``run_block`` starts the shared
   :mod:`chemrefine.engines._extopt.server` (with ``--backend mlff``)
   before ORCA, probes ``/healthz`` until the server is ready, and
   tears it down on exit.

Backend selection / model name are read from ``step.options`` in the
YAML.
"""

from __future__ import annotations

import logging
import shlex
from pathlib import Path

from chemrefine.engines._extopt.base import SERVER_URL_FILENAME
from chemrefine.engines.base import register
from chemrefine.engines.orca.engine import OrcaEngine
from chemrefine.state import StepContext

logger = logging.getLogger(__name__)

_SERVER_READY_TIMEOUT_SECONDS: int = 120


@register("mlff")
class MlffEngine(OrcaEngine):
    """ORCA optimisation backed by an MLFF gradient server."""

    name = "mlff"
    supports_nms = False  # frequencies via MLFF aren't validated yet

    # -- ORCA input customisation -----------------------------------------

    def _extra_blocks(self, ctx: StepContext) -> str:
        """Emit a ``%method ProgExt "<wrapper>"`` block tied to this step."""
        wrapper = self._wrapper_path(ctx)
        return (
            "%method\n"
            f'  ProgExt "{wrapper}"\n'
            "end"
        )

    # -- SLURM customisation ----------------------------------------------

    def _run_block(self, ctx: StepContext, inp_path: Path, out_path: Path) -> str:
        """Spin up the ExtOpt server (mlff backend), run ORCA, clean up.

        The server binds ``127.0.0.1:0`` (kernel-assigned port) and
        writes its actual URL to a sidecar file so concurrent SLURM
        jobs on the same node never collide.
        """
        options = ctx.step_cfg.options or {}
        model_name = options.get("model_name") or options.get("model") or "uma-s-1"
        task_name = options.get("task_name") or options.get("task") or "omol"
        device = options.get("device", "cuda")

        server_cmd = _server_command(
            backend="mlff",
            extra_flags=[
                ("--model", model_name),
                ("--task-name", task_name),
                ("--device", device),
            ],
        )
        return _build_extopt_run_block(
            server_cmd=server_cmd,
            orca_executable=ctx.orca_executable,
            inp_name=inp_path.name,
            out_name=out_path.name,
        )

    # -- Helpers -----------------------------------------------------------

    def _wrapper_path(self, ctx: StepContext) -> Path:
        """Path of the per-step ``ProgExt`` wrapper script.

        The script is generated by
        :func:`chemrefine.engines._extopt.protocol.write_wrapper_script`
        before ORCA runs; the engine resolves the canonical path here so
        the ORCA input can reference it before the file exists.
        """
        return (ctx.step_dir / "mlff_extopt.sh").resolve()


# ---------------------------------------------------------------------------
# Shared bash helpers (used by both Mlff and Pyscf engines)
# ---------------------------------------------------------------------------


def _server_command(
    *,
    backend: str,
    extra_flags: list[tuple[str, str]],
) -> str:
    """Build the ``python -m chemrefine.engines._extopt.server ...`` command."""
    parts = [
        "python -m chemrefine.engines._extopt.server",
        f"--backend {shlex.quote(backend)}",
        '--bind 127.0.0.1:0',
        '--url-file "$URL_FILE"',
        '--log-file "$LOG_FILE"',
        "--log-level INFO",
    ]
    for flag, value in extra_flags:
        parts.append(f"{flag} {shlex.quote(str(value))}")
    return " ".join(parts)


def _build_extopt_run_block(
    *,
    server_cmd: str,
    orca_executable: str,
    inp_name: str,
    out_name: str,
) -> str:
    """Return the bash ``run_block`` that orchestrates the ExtOpt server + ORCA.

    The block:

    * Binds the server on a kernel-assigned port (sidecar URL file).
    * Loops up to ``_SERVER_READY_TIMEOUT_SECONDS`` polling ``/healthz``,
      exiting fast if the server process dies during startup.
    * Wraps cleanup in ``trap _on_extopt_exit EXIT INT TERM`` so SLURM
      cancellation (SIGTERM), Ctrl-C (SIGINT), or normal exit all reach
      the cleanup path; ``kill -TERM`` + ``wait`` gives the server a
      chance to release GPU memory cleanly.
    """
    return (
        '# ExtOpt server lifecycle (generated by ChemRefine MLFF/PySCF engine)\n'
        f'LOG_FILE="$OUTPUT_DIR/server_${{SLURM_JOB_ID:-$$}}.log"\n'
        f'URL_FILE="$WORK_DIR/{SERVER_URL_FILENAME}"\n'
        f'SERVER_TIMEOUT={_SERVER_READY_TIMEOUT_SECONDS}\n'
        f'{server_cmd} &\n'
        'SERVER_PID=$!\n'
        '\n'
        '_on_extopt_exit() {\n'
        '  if [ -n "${SERVER_PID:-}" ]; then\n'
        '    kill -TERM "$SERVER_PID" 2>/dev/null || true\n'
        '    wait "$SERVER_PID" 2>/dev/null || true\n'
        '  fi\n'
        '}\n'
        'trap _on_extopt_exit EXIT INT TERM\n'
        '\n'
        '# Wait for /healthz; bail out fast if the server crashed during startup.\n'
        'ready=\n'
        'for i in $(seq 1 "$SERVER_TIMEOUT"); do\n'
        '  if [ -s "$URL_FILE" ] \\\n'
        '     && SERVER_URL=$(cat "$URL_FILE") \\\n'
        '     && curl -fsS --max-time 2 "http://${SERVER_URL}/healthz" >/dev/null; then\n'
        '    echo "ExtOpt server ready at $SERVER_URL after ${i}s"\n'
        '    ready=1\n'
        '    break\n'
        '  fi\n'
        '  if ! ps -p "$SERVER_PID" >/dev/null; then\n'
        '    echo "ExtOpt server crashed during startup; log follows:" >&2\n'
        '    cat "$LOG_FILE" >&2 || true\n'
        '    exit 1\n'
        '  fi\n'
        '  sleep 1\n'
        'done\n'
        '[ -n "$ready" ] || {\n'
        '  echo "ExtOpt server did not become ready within ${SERVER_TIMEOUT}s; log follows:" >&2\n'
        '  cat "$LOG_FILE" >&2 || true\n'
        '  exit 1\n'
        '}\n'
        '\n'
        'export OMP_NUM_THREADS=1\n'
        f'{orca_executable} {inp_name} > "$OUTPUT_DIR/{out_name}"'
    )
