"""Bash that orchestrates the ExtOpt HTTP server alongside ORCA in one SLURM job.

The two engines that drive ORCA through an external optimizer (MLIP and
PySCF) emit a SLURM ``run_block`` that spins up the shared
:mod:`chemrefine.engines._backend_server.server`, polls ``/healthz`` until it is
ready, runs ORCA, and tears the server down on exit. This module owns
that bash so neither engine ends up importing helpers from the other.
"""

from __future__ import annotations

import shlex

from chemrefine.engines._backend_server.base import DEFAULT_BIND_HOST, SERVER_URL_FILENAME
from chemrefine.state import RunBlock

_SERVER_READY_TIMEOUT_SECONDS: int = 120


def server_command(
    *,
    backend: str,
    extra_tokens: list[str],
    interpreter: str = "python",
) -> str:
    """Build the ``<python> -m chemrefine.engines._backend_server.server ...`` command.

    ``interpreter`` is the Python that hosts the backend server — the orchestrator's
    ``python`` by default, or a managed backend env's interpreter resolved by
    :func:`chemrefine.engines._provision.resolve_launcher` (that env just needs
    ``chemrefine[<backend extra>]`` installed). ``extra_tokens`` is a flat list of CLI
    tokens (e.g. ``["--foo", "bar", "--baz"]``) emitted by the backend's
    :meth:`ComputeBackend.server_cli_from_options`. Keeping them as one list keeps
    key-value flags and bool flags symmetric.
    """
    parts = [
        f"{shlex.quote(interpreter)} -m chemrefine.engines._backend_server.server",
        f"--backend {shlex.quote(backend)}",
        f"--bind {DEFAULT_BIND_HOST}:0",
        '--url-file "$URL_FILE"',
        '--log-file "$LOG_FILE"',
        "--log-level INFO",
    ]
    parts.extend(shlex.quote(token) for token in extra_tokens)
    return " ".join(parts)


def build_extopt_run_block(
    *,
    server_cmd: str,
    orca_command: str,
    pal: int,
) -> RunBlock:
    """Return the :class:`~chemrefine.engines.api.RunBlock` orchestrating the ExtOpt server + ORCA.

    The ``body``:

    * Binds the server on a kernel-assigned port (sidecar URL file).
    * Loops up to ``_SERVER_READY_TIMEOUT_SECONDS`` polling ``/healthz``,
      exiting fast if the server process dies during startup.

    The ``cleanup`` stops the server — ``kill -TERM`` + ``wait``, which gives it a chance to
    release GPU memory — and :func:`chemrefine.slurm.script._run_body_lines` interpolates it
    into the script's one ``EXIT`` handler, so it runs on any exit path including SLURM
    cancellation and Ctrl-C.

    Returning teardown as *data* is the whole point of the two-field type. A ``trap
    _on_extopt_exit EXIT INT TERM`` emitted inline here would *replace* the surrounding
    script's handler, since bash keeps one per signal — costing every ExtOpt job its
    copy-back (``.gbw`` / ``.hess`` / ``.property.json`` / the optimised ``.xyz``), its
    ``output_dirs`` copy (the only delivery path for ``pyscf-extopt``'s ``save_tensors``),
    its runlog footer and its scratch teardown, and leaking ``$WORK_DIR`` every run. None of
    that surfaces in the results: ORCA redirects its ``.out`` straight to ``$OUTPUT_DIR``, so
    parsing still succeeds.

    ``orca_command`` arrives already assembled and quoted from
    :meth:`chemrefine.engines.orca.engine.OrcaEngine.orca_command` — the same string the
    plain ORCA path runs — rather than being re-interpolated here from a raw executable,
    which is what keeps the two paths' quoting from diverging.

    Public, not underscored, because that is the whole reason this module exists: the
    MLIP and PySCF ExtOpt engines both call it, and the alternative is one of them
    importing the other's helper.
    """
    cleanup = (
        'if [ -n "${SERVER_PID:-}" ]; then\n'
        '  kill -TERM "$SERVER_PID" 2>/dev/null || true\n'
        '  wait "$SERVER_PID" 2>/dev/null || true\n'
        "fi"
    )
    body = (
        "# ExtOpt server lifecycle (generated by ChemRefine MLIP/PySCF engine)\n"
        f'LOG_FILE="$OUTPUT_DIR/server_${{SLURM_JOB_ID:-$$}}.log"\n'
        f'URL_FILE="$WORK_DIR/{SERVER_URL_FILENAME}"\n'
        f"SERVER_TIMEOUT={_SERVER_READY_TIMEOUT_SECONDS}\n"
        # The server is the compute half of this job, and it inherits its thread count from
        # this environment at launch: exported before the `&`, so torch/MKL see the step's
        # own budget. Left uncapped they take every core on the node while the throttler
        # charges this job `pal` — invisible under SLURM's cgroups, an oversubscription on
        # every local run.
        f"export OMP_NUM_THREADS={pal}\n"
        f"export MKL_NUM_THREADS={pal}\n"
        f"{server_cmd} &\n"
        "SERVER_PID=$!\n"
        "\n"
        "# Wait for /healthz; bail out fast if the server crashed during startup.\n"
        "ready=\n"
        'for i in $(seq 1 "$SERVER_TIMEOUT"); do\n'
        '  if [ -s "$URL_FILE" ] \\\n'
        '     && SERVER_URL=$(cat "$URL_FILE") \\\n'
        '     && curl -fsS --max-time 2 "http://${SERVER_URL}/healthz" >/dev/null; then\n'
        '    echo "ExtOpt server ready at $SERVER_URL after ${i}s"\n'
        "    ready=1\n"
        "    break\n"
        "  fi\n"
        '  if ! ps -p "$SERVER_PID" >/dev/null; then\n'
        '    echo "ExtOpt server crashed during startup; log follows:" >&2\n'
        '    cat "$LOG_FILE" >&2 || true\n'
        "    exit 1\n"
        "  fi\n"
        "  sleep 1\n"
        "done\n"
        '[ -n "$ready" ] || {\n'
        '  echo "ExtOpt server did not become ready within ${SERVER_TIMEOUT}s; log follows:" >&2\n'
        '  cat "$LOG_FILE" >&2 || true\n'
        "  exit 1\n"
        "}\n"
        "\n"
        # Re-exported down to 1 for ORCA only: in ExtOpt mode ORCA is a stepper whose math
        # is done by the server, and the server keeps the threads it inherited above.
        "export OMP_NUM_THREADS=1\n"
        f"{orca_command}"
    )
    return RunBlock(body=body, cleanup=cleanup)
